name: Java CI

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    container:
      image: lakruzz/androiddev
      volumes:
        - $(pwd):/app
      options: --workdir /app

    steps:
      - name: androiddev
        run: gradle

      
