# https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container#example-running-a-job-within-a-container
name: Java CI

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    container:
      image: lakruzz/androiddev
    steps:
      - run: echo - ${{ github.repository }}
      - run: git clone --depth 1 https://github.com/${{github.repository}}.git repo && \
             cd repo && \
             pwd && ls
      - run: env | sort
      - run: gradle

      
