# https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container#example-running-a-job-within-a-container
name: Java CI

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    container:
      image: lakruzz/androiddev
    steps:
      - name: Clone the git repo ${{ github.repository }}
        run: git clone --depth 1 https://github.com/${{github.repository}}.git . 
      - name: Output state
        run: |
          pwd
          ls
          env | sort
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build using gradle (using the version installed on the docker image)
        run: gradle
      - name: Output state
        run: |
          pwd
          ls
          env | sort
      - name: Build again using the gradlew script in the repo (pulling the entire Gradle version off then internet)
        run: ./gradlew 
      - name: Build with Gradle Action
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      
