# https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container#example-running-a-job-within-a-container
name: Java CI

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    container:
      image: lakruzz/jekyll-plus
      options: --entrypoint=jekyll
    steps:
      - run: ls

      
