# https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container#example-running-a-job-within-a-container
name: Java CI

on: [push]

jobs:
  docker-gradle:
    runs-on: ubuntu-latest
    container:
      image: lakruzz/androiddev
    steps:
      - name: Clone the git repo ${{ github.repository }}
        run: git clone --depth 1 https://github.com/${{github.repository}}.git . 
      - name: Output state
        run: |
          pwd
          ls
          env | sort
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build using gradle (using the version installed on the docker image)
        run: gradle

  docker-gradlew:
    runs-on: ubuntu-latest
    container:
      image: lakruzz/androiddev
    steps:
      - name: Clone the git repo ${{ github.repository }}
        run: git clone --depth 1 https://github.com/${{github.repository}}.git . 
      - name: Output state
        run: |
          pwd
          ls
          env | sort
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build again using the gradlew script in the repo (pulling the entire Gradle version off then internet)
        run: ./gradlew 
  
  action-gradlew:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build      
