# https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container#example-running-a-job-within-a-container
name: Java CI

on: [push]

jobs:
  clone:
    runs-on: ubuntu-latest
    container:
      image: lakruzz/androiddev
    steps:
      - name: Clone the git repo ${{ github.repository }}
        run: git clone --depth 1 https://github.com/${{github.repository}}.git . 
      - uses: actions/cache@v3
        id: gitrepo
        with:
          path: .
          key: ${{ github.repository }}-${{ github.sha }}
      - name: Output state
        run: |
          pwd
          ls
          env | sort
          
 
  docker-gradle:
    needs: clone
    runs-on: ubuntu-latest
    container:
      image: lakruzz/androiddev
    steps:
      - uses: actions/cache@v3
        id: gitrepo
        with:
          path: .
          key: ${{ github.repository }}-${{ github.sha }}
      - name: Output state
        run: |
          pwd
          ls
          env | sort
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build using gradle (using the version installed on the docker image)
        run: gradle

  docker-gradlew:
    needs: clone
    runs-on: ubuntu-latest
    container:
      image: lakruzz/androiddev
    steps:
      - uses: actions/cache@v3
        id: gitrepo
        with:
          path: .
          key: ${{ github.repository }}-${{ github.sha }}
      - name: Output state
        run: |
          pwd
          ls
          env | sort
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build again using the gradlew script in the repo (pulling the entire Gradle version off then internet)
        run: ./gradlew 
  
  action-gradlew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Output state
        run: |
          pwd
          ls
          env | sort
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle Action
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: build
